import React, { useEffect, useState } from 'react';
import { ArrowDownAZ, ArrowRight, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../api/axiosInstance';

export default function Members() {
  const [data, setData] = useState({ members: [], pages: 0 }); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState('createdAt'); const [direction, setDirection] = useState('desc'); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => window.clearTimeout(timer); }, [search]);
  useEffect(() => { setLoading(true); api.get(`/members?page=${page}&search=${encodeURIComponent(query)}&sort=${sort}&direction=${direction}`).then(response => setData(response.data)).catch(() => setData({ members: [], pages: 0, total: 0 })).finally(() => setLoading(false)); }, [page, query, sort, direction]);
  function changeSort(event) { setSort(event.target.value); setPage(1); }
  return <div className="page-width app-page"><div className="page-heading"><div><span className="eyebrow">DIRECTORY</span><h1>Your regulars.</h1></div><div className="member-count">{data.total || 0} members</div></div><div className="directory-toolbar"><div className="small-search"><Search size={17} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name or phone" /></div><div className="directory-controls"><select value={sort} onChange={changeSort}><option value="createdAt">Recent joins</option><option value="name">Name</option><option value="balance">Balance</option><option value="lifetimePoints">Lifetime points</option><option value="tier">Tier</option></select><button onClick={() => setDirection(direction === 'asc' ? 'desc' : 'asc')} title="Reverse sort"><ArrowDownAZ size={16} /> {direction === 'asc' ? 'A-Z' : 'Z-A'}</button></div></div>{loading ? <div className="loading">Loading members...</div> : data.members.length ? <div className="table"><div className="table-head"><span>Member</span><span>Tier</span><span>Balance</span><span>Lifetime points</span></div>{data.members.map(m => <Link to={`/members/${m._id}`} className="table-row" key={m._id}><span className="person"><i>{m.name.slice(0, 2).toUpperCase()}</i><b>{m.name}<small>{m.phone}</small></b></span><span><em className={`tier-badge ${m.tier.toLowerCase()}`}>{m.tier}</em></span><strong>{m.balance} pts</strong><span>{m.lifetimePoints} pts <ArrowRight size={15} /></span></Link>)}</div> : <div className="empty-state directory-empty"><Search size={32} /><h2>No members found.</h2><p>Try a different name or phone number.</p></div>}<div className="pagination"><button disabled={page <= 1 || loading} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {Math.max(data.pages, 1)}</span><button disabled={page >= data.pages || loading} onClick={() => setPage(page + 1)}>Next</button></div></div>;
}
