import React, { useEffect, useState } from 'react';
import { ArrowRight, Coffee, Gift, Tag, TrendingUp, Utensils } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../api/axiosInstance';

export default function MemberHome() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get('/member/home').then(response => setData(response.data)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="member-loading">Loading your lounge...</div>;
  if (!data) return <div className="member-empty">We could not find your member profile.</div>;
  const next = data.member.tier === 'Bronze' ? 500 : data.member.tier === 'Silver' ? 1500 : null; const progress = next ? Math.min(data.member.lifetimePoints / next * 100, 100) : 100;
  return <div className="member-page page-width"><div className="member-hero-image"><img src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1800&q=85" alt="Coffee on a café table" /><div><span className="eyebrow">YOUR MEMBER LOUNGE</span><h1>Good to see you,<br /><em>{data.member.name}.</em></h1><p>Every cup, a little closer to something lovely.</p></div><span className={`tier-badge ${data.member.tier.toLowerCase()}`}>{data.member.tier} tier</span></div><section className="member-balance"><div><span>Available balance</span><strong>{data.member.balance.toLocaleString()} <small>points</small></strong><p>Use them on your next treat.</p></div><Coffee size={47} /></section><section className="member-progress"><div><span className="eyebrow">TIER PROGRESS</span><h2>{next ? `${Math.max(next - data.member.lifetimePoints, 0)} points until ${data.member.tier === 'Bronze' ? 'Silver' : 'Gold'}` : 'You have reached the top tier.'}</h2></div><b>{data.member.lifetimePoints} {next ? `/ ${next}` : 'pts'}</b><div className="progress"><i style={{ width: `${progress}%` }} /></div></section><div className="member-quick-links"><Link to="/member/menu"><Utensils size={19} /><b>View menu</b><small>Find your next cup</small><ArrowRight size={15} /></Link><Link to="/member/redeem"><Gift size={19} /><b>Rewards</b><small>Browse your treats</small><ArrowRight size={15} /></Link><Link to="/member/offers"><Tag size={19} /><b>Offers</b><small>Member-only extras</small><ArrowRight size={15} /></Link></div><div className="member-section-heading"><h2>Recent activity</h2><Link to="/member/visits">View all visits <ArrowRight size={15} /></Link></div>{data.transactions.length ? <div className="member-history">{data.transactions.map(transaction => <div className="member-history-row" key={transaction._id}><span className={`history-icon ${transaction.type}`}><TrendingUp size={16} /></span><span><b>{transaction.description}</b><small>{new Date(transaction.createdAt).toLocaleDateString()}</small></span><strong className={transaction.type}>{transaction.points > 0 ? '+' : ''}{transaction.points} pts</strong></div>)}</div> : <div className="member-empty small">Your first visit is waiting to be recorded.</div>}</div>;
}
