import React, { useEffect, useState } from 'react';
import { TrendingUp } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axiosInstance';

const thresholds = { Bronze: 500, Silver: 1500, Gold: null };
export default function MemberProfile() {
  const { id } = useParams(); const [member, setMember] = useState(null); const [history, setHistory] = useState({ transactions: [], pages: 0 }); const [type, setType] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); Promise.all([api.get(`/members/${id}`), api.get(`/members/${id}/transactions?page=${page}&type=${type}&from=${from}&to=${to}`)]).then(([memberResponse, historyResponse]) => { setMember(memberResponse.data.member); setHistory(historyResponse.data); }).finally(() => setLoading(false)); }, [id, page, type, from, to]);
  if (loading && !member) return <div className="loading">Loading member...</div>; if (!member) return <div className="empty-state page-width"><h2>Member not found.</h2><Link className="button primary" to="/members">Back to members</Link></div>;
  const next = thresholds[member.tier]; const progress = next ? Math.min((member.lifetimePoints / next) * 100, 100) : 100; const needed = next ? Math.max(next - member.lifetimePoints, 0) : 0;
  return <div className="page-width app-page"><Link to="/members" className="back-link">← Back to members</Link><div className="profile-head"><div className="member-avatar large">{member.name.slice(0, 2).toUpperCase()}</div><div><span className="eyebrow">MEMBER PROFILE</span><h1>{member.name}</h1><p>{member.phone} · Joined {new Date(member.createdAt).toLocaleDateString()}</p></div><em className={`tier-badge ${member.tier.toLowerCase()}`}>{member.tier}</em></div><div className="profile-stats"><div><span>Available points</span><strong>{member.balance}</strong></div><div><span>Lifetime points</span><strong>{member.lifetimePoints}</strong></div><div><span>Visits recorded</span><strong>{history.total || 0}</strong></div></div><section className="tier-progress"><div><span className="eyebrow">TIER PROGRESS</span><h2>{next ? `${needed} points to ${member.tier === 'Bronze' ? 'Silver' : 'Gold'}` : 'Top tier unlocked'}</h2></div><b>{member.lifetimePoints} {next ? `/ ${next}` : 'pts'}</b><div className="progress"><i style={{ width: `${progress}%` }} /></div></section><div className="history-heading"><h2 className="history-title">Transaction history</h2><div className="history-filters"><select value={type} onChange={event => { setType(event.target.value); setPage(1); }}><option value="">All activity</option><option value="earn">Earned</option><option value="redeem">Redeemed</option></select><input type="date" value={from} onChange={event => { setFrom(event.target.value); setPage(1); }} /><input type="date" value={to} onChange={event => { setTo(event.target.value); setPage(1); }} /></div></div>{history.transactions.length ? <div className="history">{history.transactions.map(transaction => <div className="history-row" key={transaction._id}><span className={`history-icon ${transaction.type}`}><TrendingUp size={16} /></span><span><b>{transaction.description}</b><small>{new Date(transaction.createdAt).toLocaleString()}</small></span><strong className={transaction.type}>{transaction.points > 0 ? '+' : ''}{transaction.points} pts</strong></div>)}</div> : <div className="empty-state history-empty"><h2>No transactions yet.</h2><p>Earned and redeemed points will appear here.</p></div>}<div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {Math.max(history.pages, 1)}</span><button disabled={page >= history.pages} onClick={() => setPage(page + 1)}>Next</button></div></div>;
}
