const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const mongoose = require('mongoose');
const { StaffUser } = require('../models');
const store = require('../localStore');

const tokenFor = (user) => jwt.sign({ id: user._id, role: user.role }, process.env.JWT_SECRET || 'development-secret', { expiresIn: '8h' });
async function register(req, res) { try { const { name, email, password } = req.body; const normalizedEmail = email.toLowerCase(); if (!store.isMongoReady(mongoose)) { const data = store.read(); if (data.staffUsers.some(user => user.email === normalizedEmail)) return res.status(409).json({ message: 'Email already registered.' }); const user = { _id: store.id('staff'), name, email: normalizedEmail, passwordHash: await bcrypt.hash(password, 10), role: 'staff', createdAt: store.now() }; data.staffUsers.push(user); store.write(data); return res.status(201).json({ token: tokenFor(user), user: { name: user.name, email: user.email, role: user.role } }); } const passwordHash = await bcrypt.hash(password, 10); const user = await StaffUser.create({ name, email: normalizedEmail, passwordHash }); res.status(201).json({ token: tokenFor(user), user: { name: user.name, email: user.email, role: user.role } }); } catch (error) { res.status(error.code === 11000 ? 409 : 400).json({ message: error.code === 11000 ? 'Email already registered.' : error.message }); } }
async function login(req, res) { const email = req.body.email?.toLowerCase(); if (!store.isMongoReady(mongoose)) { const data = store.read(); const user = data.staffUsers.find(item => item.email === email); if (!user || !(await bcrypt.compare(req.body.password || '', user.passwordHash))) return res.status(401).json({ message: 'Invalid email or password.' }); return res.json({ token: tokenFor(user), user: { name: user.name, email: user.email, role: user.role } }); } const user = await StaffUser.findOne({ email }); if (!user || !(await bcrypt.compare(req.body.password || '', user.passwordHash))) return res.status(401).json({ message: 'Invalid email or password.' }); res.json({ token: tokenFor(user), user: { name: user.name, email: user.email, role: user.role } }); }
module.exports = { register, login };