const mongoose = require('mongoose');
const { Member, Transaction, RedemptionItem, Tier } = require('../models');
const store = require('../localStore');

const tierFor = async (lifetimePoints) => (await Tier.findOne({ threshold: { $lte: lifetimePoints } }).sort({ threshold: -1 })) || { name: 'Bronze', multiplier: 1 };
const localTierFor = (data, points) => store.tierFor(data, points);
const safeSearch = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').toLowerCase();

async function listMembers(req, res) {
  const page = Math.max(Number(req.query.page) || 1, 1); const limit = Math.min(Number(req.query.limit) || 10, 50); const search = safeSearch(req.query.search || '');
  if (!store.isMongoReady(mongoose)) { const data = store.read(); let members = data.members.filter(member => !search || member.phone.toLowerCase().includes(search) || member.name.toLowerCase().includes(search)); const field = ['name', 'balance', 'lifetimePoints', 'tier', 'createdAt'].includes(req.query.sort) ? req.query.sort : 'createdAt'; const direction = req.query.direction === 'asc' ? 1 : -1; members.sort((a, b) => String(a[field]).localeCompare(String(b[field]), undefined, { numeric: true }) * direction); const total = members.length; return res.json({ members: members.slice((page - 1) * limit, page * limit), page, pages: Math.ceil(total / limit), total }); }
  const query = search ? { $or: [{ phone: new RegExp(search, 'i') }, { name: new RegExp(search, 'i') }] } : {}; const sortField = ['name', 'balance', 'lifetimePoints', 'tier', 'createdAt'].includes(req.query.sort) ? req.query.sort : 'createdAt'; const direction = req.query.direction === 'asc' ? 1 : -1; const [members, total] = await Promise.all([Member.find(query).sort({ [sortField]: direction }).skip((page - 1) * limit).limit(limit), Member.countDocuments(query)]); res.json({ members, page, pages: Math.ceil(total / limit), total });
}

async function createMember(req, res) { try { if (!store.isMongoReady(mongoose)) { const data = store.read(); if (data.members.some(member => member.phone === req.body.phone.trim())) return res.status(409).json({ message: 'A member with that phone already exists.' }); const member = { _id: store.id('member'), name: req.body.name.trim(), phone: req.body.phone.trim(), email: req.body.email?.trim().toLowerCase(), tier: 'Bronze', balance: 0, lifetimePoints: 0, createdAt: store.now(), updatedAt: store.now() }; data.members.push(member); store.write(data); return res.status(201).json(member); } res.status(201).json(await Member.create({ name: req.body.name.trim(), phone: req.body.phone.trim(), email: req.body.email?.trim().toLowerCase() })); } catch (error) { res.status(error.code === 11000 ? 409 : 400).json({ message: error.code === 11000 ? 'A member with that phone already exists.' : error.message }); } }

async function getMember(req, res) { if (!store.isMongoReady(mongoose)) { const member = store.read().members.find(item => item._id === req.params.id); if (!member) return res.status(404).json({ message: 'Member not found' }); return res.json({ member }); } const member = await Member.findById(req.params.id); if (!member) return res.status(404).json({ message: 'Member not found' }); res.json({ member }); }

async function recordPurchase(req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); const member = data.members.find(item => item._id === req.params.id); if (!member) return res.status(404).json({ message: 'Member not found' }); const amount = Number(req.body.amount); const tier = localTierFor(data, member.lifetimePoints); const points = Math.floor(amount * Number(process.env.POINTS_PER_RUPEE || 0.1) * tier.multiplier); const transaction = { _id: store.id('transaction'), member: member._id, type: 'earn', amount, points, description: req.body.description || 'Purchase', createdAt: store.now() }; data.transactions.push(transaction); member.balance += points; member.lifetimePoints += points; member.tier = localTierFor(data, member.lifetimePoints).name; member.updatedAt = store.now(); store.write(data); return res.status(201).json({ member, transaction }); } const member = await Member.findById(req.params.id); if (!member) return res.status(404).json({ message: 'Member not found' }); const amount = Number(req.body.amount); const tier = await tierFor(member.lifetimePoints); const points = Math.floor(amount * Number(process.env.POINTS_PER_RUPEE || 0.1) * tier.multiplier); const transaction = await Transaction.create({ member: member._id, type: 'earn', amount, points, description: req.body.description || 'Purchase' }); member.balance += points; member.lifetimePoints += points; member.tier = (await tierFor(member.lifetimePoints)).name; await member.save(); res.status(201).json({ member: await Member.findById(member._id), transaction }); }

async function redeemReward(req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); const member = data.members.find(item => item._id === req.params.id); const item = data.redemptionItems.find(reward => reward._id === req.body.itemId && reward.available); if (!member || !item) return res.status(404).json({ message: 'Member or reward not found.' }); if (member.balance < item.cost) return res.status(400).json({ message: `You need ${item.cost - member.balance} more points for this reward.` }); const transaction = { _id: store.id('transaction'), member: member._id, type: 'redeem', amount: 0, points: -item.cost, description: item.name, createdAt: store.now() }; data.transactions.push(transaction); member.balance -= item.cost; member.updatedAt = store.now(); store.write(data); return res.status(201).json({ member, transaction }); } const member = await Member.findById(req.params.id); const item = await RedemptionItem.findOne({ _id: req.body.itemId, available: true }); if (!member || !item) return res.status(404).json({ message: 'Member or reward not found.' }); if (member.balance < item.cost) return res.status(400).json({ message: `You need ${item.cost - member.balance} more points for this reward.` }); const transaction = await Transaction.create({ member: member._id, type: 'redeem', amount: 0, points: -item.cost, description: item.name }); member.balance -= item.cost; await member.save(); res.status(201).json({ member: await Member.findById(member._id), transaction }); }

async function listTransactions(req, res) { const page = Math.max(Number(req.query.page) || 1, 1); const limit = Math.min(Number(req.query.limit) || 10, 50); if (!store.isMongoReady(mongoose)) { const data = store.read(); let transactions = data.transactions.filter(item => item.member === req.params.id); if (['earn', 'redeem'].includes(req.query.type)) transactions = transactions.filter(item => item.type === req.query.type); if (req.query.from) transactions = transactions.filter(item => new Date(item.createdAt) >= new Date(req.query.from)); if (req.query.to) { const to = new Date(req.query.to); to.setHours(23, 59, 59, 999); transactions = transactions.filter(item => new Date(item.createdAt) <= to); } transactions.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)); const total = transactions.length; return res.json({ transactions: transactions.slice((page - 1) * limit, page * limit), page, pages: Math.ceil(total / limit), total }); } const query = { member: req.params.id }; if (['earn', 'redeem'].includes(req.query.type)) query.type = req.query.type; if (req.query.from || req.query.to) { query.createdAt = {}; if (req.query.from) query.createdAt.$gte = new Date(req.query.from); if (req.query.to) { const to = new Date(req.query.to); to.setHours(23, 59, 59, 999); query.createdAt.$lte = to; } } const [transactions, total] = await Promise.all([Transaction.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), Transaction.countDocuments(query)]); res.json({ transactions, page, pages: Math.ceil(total / limit), total }); }

module.exports = { listMembers, createMember, getMember, recordPurchase, redeemReward, listTransactions };
