const mongoose = require('mongoose');
const { Member, Transaction, RedemptionItem, Offer } = require('../models');
const store = require('../localStore');
const bcrypt = require('bcryptjs');
async function home(req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); const member = data.members.find(item => item._id === req.staff.memberId); if (!member) return res.status(404).json({ message: 'Member profile not found.' }); const transactions = data.transactions.filter(item => item.member === member._id).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 10); return res.json({ member, transactions }); } const member = await Member.findById(req.staff.memberId); if (!member) return res.status(404).json({ message: 'Member profile not found.' }); res.json({ member, transactions: await Transaction.find({ member: member._id }).sort({ createdAt: -1 }).limit(10) }); }
async function rewards(_req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); return res.json({ items: data.redemptionItems.filter(item => item.available) }); } res.json({ items: await RedemptionItem.find({ available: true }) }); }
async function redeem(req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); const member = data.members.find(item => item._id === req.staff.memberId); const item = data.redemptionItems.find(reward => reward._id === req.body.itemId && reward.available); if (!member || !item) return res.status(404).json({ message: 'Member or reward not found.' }); if (member.balance < item.cost) return res.status(400).json({ message: `You need ${item.cost - member.balance} more points for this reward.` }); const transaction = { _id: store.id('transaction'), member: member._id, type: 'redeem', amount: 0, points: -item.cost, description: item.name, createdAt: store.now() }; data.transactions.push(transaction); member.balance -= item.cost; member.updatedAt = store.now(); store.write(data); return res.status(201).json({ member, transaction }); } const member = await Member.findById(req.staff.memberId); const item = await RedemptionItem.findOne({ _id: req.body.itemId, available: true }); if (!member || !item) return res.status(404).json({ message: 'Member or reward not found.' }); if (member.balance < item.cost) return res.status(400).json({ message: `You need ${item.cost - member.balance} more points for this reward.` }); const transaction = await Transaction.create({ member: member._id, type: 'redeem', amount: 0, points: -item.cost, description: item.name }); member.balance -= item.cost; await member.save(); res.status(201).json({ member, transaction }); }
async function offers(_req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); return res.json({ offers: data.offers || [] }); } return res.json({ offers: await Offer.find({ active: true }).sort({ validTill: 1 }) }); }
async function memberVisits(req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); const transactions = data.transactions.filter(item => item.member === req.staff.memberId && item.type === 'earn').sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)); return res.json({ transactions }); } const transactions = await Transaction.find({ member: req.staff.memberId, type: 'earn' }).sort({ createdAt: -1 }); res.json({ transactions }); }
async function getOwnProfile(req, res) { if (!store.isMongoReady(mongoose)) { const data = store.read(); const member = data.members.find(item => item._id === req.staff.memberId); if (!member) return res.status(404).json({ message: 'Member profile not found.' }); return res.json({ member: { ...member, password: undefined } }); } const member = await Member.findById(req.staff.memberId).select('-passwordHash'); if (!member) return res.status(404).json({ message: 'Member profile not found.' }); res.json({ member }); }
async function updateOwnProfile(req, res) { const { name, phone, email, password, profilePhoto } = req.body; if (!store.isMongoReady(mongoose)) { const data = store.read(); const member = data.members.find(item => item._id === req.staff.memberId); const user = (data.memberUsers || []).find(item => item.memberId === req.staff.memberId); if (!member || !user) return res.status(404).json({ message: 'Member profile not found.' }); if (phone && data.members.some(item => item.phone === phone && item._id !== member._id)) return res.status(409).json({ message: 'That phone number is already in use.' }); Object.assign(member, { name: name || member.name, phone: phone || member.phone, email: email ?? member.email, profilePhoto: profilePhoto ?? member.profilePhoto, updatedAt: store.now() }); Object.assign(user, { name: member.name, phone: member.phone, email: member.email, profilePhoto: member.profilePhoto }); if (password) user.passwordHash = await bcrypt.hash(password, 10); store.write(data); return res.json({ member }); } const member = await Member.findById(req.staff.memberId); const user = await MemberUser.findOne({ member: member?._id }); if (!member || !user) return res.status(404).json({ message: 'Member profile not found.' }); if (phone && phone !== member.phone && await Member.exists({ phone })) return res.status(409).json({ message: 'That phone number is already in use.' }); Object.assign(member, { name: name || member.name, phone: phone || member.phone, email: email ?? member.email, profilePhoto: profilePhoto ?? member.profilePhoto }); Object.assign(user, { name: member.name, phone: member.phone, email: member.email, profilePhoto: member.profilePhoto }); if (password) user.passwordHash = await bcrypt.hash(password, 10); await Promise.all([member.save(), user.save()]); res.json({ member }); }
module.exports = { home, rewards, redeem, offers, memberVisits, getOwnProfile, updateOwnProfile };
