const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const mongoose = require('mongoose');
const { Member, MemberUser } = require('../models');
const store = require('../localStore');
const tokenFor = user => jwt.sign({ id: user._id, memberId: user.member || user.memberId, role: 'member' }, process.env.JWT_SECRET || 'development-secret', { expiresIn: '30d' });

async function register(req, res) { try { const { name, phone, email, password } = req.body; if (!store.isMongoReady(mongoose)) { const data = store.read(); data.memberUsers = data.memberUsers || []; if (data.memberUsers.some(user => user.phone === phone)) return res.status(409).json({ message: 'A member account with that phone already exists.' }); let member = data.members.find(item => item.phone === phone); if (!member) { member = { _id: store.id('member'), name, phone, email: email || '', tier: 'Bronze', balance: 0, lifetimePoints: 0, createdAt: store.now(), updatedAt: store.now() }; data.members.push(member); } const user = { _id: store.id('member-user'), name, phone, email: email || '', passwordHash: await bcrypt.hash(password, 10), memberId: member._id, role: 'member', createdAt: store.now() }; data.memberUsers.push(user); store.write(data); return res.status(201).json({ token: tokenFor(user), user: { name, phone, email, role: 'member' } }); } const existing = await MemberUser.findOne({ phone }); if (existing) return res.status(409).json({ message: 'A member account with that phone already exists.' }); let member = await Member.findOne({ phone }); if (!member) member = await Member.create({ name, phone, email }); const user = await MemberUser.create({ name, phone, email, passwordHash: await bcrypt.hash(password, 10), member: member._id }); res.status(201).json({ token: tokenFor(user), user: { name, phone, email, role: 'member' } }); } catch (error) { res.status(400).json({ message: error.message }); } }
async function login(req, res) { const { phone, password } = req.body; if (!store.isMongoReady(mongoose)) { const data = store.read(); const user = (data.memberUsers || []).find(item => item.phone === phone); if (!user || !(await bcrypt.compare(password, user.passwordHash))) return res.status(401).json({ message: 'Invalid phone number or password.' }); return res.json({ token: tokenFor(user), user: { name: user.name, phone: user.phone, email: user.email, role: 'member' } }); } const user = await MemberUser.findOne({ phone }); if (!user || !(await bcrypt.compare(password, user.passwordHash))) return res.status(401).json({ message: 'Invalid phone number or password.' }); res.json({ token: tokenFor(user), user: { name: user.name, phone: user.phone, email: user.email, role: 'member' } }); }
module.exports = { register, login };
